### PR TITLE
Fixed the Bank Address mandatory field

### LINKED ISSUE #28351: Bank address mandatory field does not work. [Bank transfer module]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Editing the account details in the bank transfer module, the "Bank address" field is marked as mandatory, but when leaving it empty it still saves without any issues.
image

### Expected behavior

Should not allow to save without any bank address.

### Steps to reproduce

1. Go to Modules -> Module manager
2. Enter the default Prestashop module "Bank transfer".
3. Enter all the details, leave the "Bank address" field empty.
4. Press "Save".

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

Bank transfer v2.1.1

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Fixed the Bank Address mandatory field
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/PrestaShop#28351
| How to test?  | Cf. PrestaShop/PrestaShop#28351

### CODE REVIEW

**Comment by Progi1984** [comment]
(Ping @Julievrz for the new wording).

**Comment by Julievrz** [comment]
I cannot add the "wording ✔️" label but it's ok for me

File: ps_wirepayment.php [hunk 1]
```diff
@@ -129,6 +129,8 @@ protected function _postValidation()
                 $this->_postErrors[] = $this->trans('Account details are required.', [], 'Modules.Wirepayment.Admin');
             } elseif (!Tools::getValue('BANK_WIRE_OWNER')) {
                 $this->_postErrors[] = $this->trans('Account owner is required.', [], 'Modules.Wirepayment.Admin');
+            } elseif (!Tools::getValue('BANK_WIRE_ADDRESS')) {
+                $this->_postErrors[] = $this->trans('Account address is required.', [], 'Modules.Wirepayment.Admin');
```
Comment (NeOMakinG) [inline ps_wirepayment.php]: Do we really need the `elseif`? I guess all of these errors could be shown at the same time, it would avoid filling one field at a time to see errors

Comment (Progi1984) [reply ps_wirepayment.php]: @NeOMakinG You're right. It's fixed.

**Review by NeOMakinG — DISMISSED** [review]

**Review by ghost — DISMISSED** [review]

**Review by khouloudbelguith — COMMENTED** [review]
Hello @Progi1984, @Julievrz,

I checked with 1.7.8.x & 8.0.x.

1. I have the same issue following these steps:
2. Install this PR of the module `ps_wirepayment`
3. Click on configure
4. Click on save

The alert of the bank address is wrong, it is displayed `Account address is required.` but it should be `Bank address is required.`

I think an account address is not similar to a Bank address.

image

What do you think?

Thanks!

**Comment by Julievrz** [comment]
> Hello @Progi1984, @Julievrz,
> 
> I checked with 1.7.8.x & 8.0.x.
> 
> 1. I have the same issue following these steps:
> 2. Install this PR of the module `ps_wirepayment`
> 3. Click on configure
> 4. Click on save
> 
> The alert of the bank address is wrong, it is displayed `Account address is required.` but it should be `Bank address is required.`
> 
> I think an account address is not similar to a Bank address.
> 
> image
> 
> What do you think?
> 
> Thanks!

You're right, we must be consistent -> Bank address. Thanks!

**Comment by Progi1984** [comment]
@Julievrz I have fixed the wording

@okom3pom & @NeOMakinG : Hi, when you have the time, could you review this PR (ba11cc9 added) ?

**Comment by Progi1984** [comment]
@PrestaShop/committers & @PrestaShop/prestashop-maintainers : I rebase my PR. Please review when you have some free time.

**Review by NeOMakinG — APPROVED** [review]
🍬

**Review by atomiix — APPROVED** [review]

**Review by SD1982 — APPROVED** [review]
LGTM :+1: 
Tested with php 7.3 thanks @Progi1984

**Comment by jolelievre** [comment]
Thanks @SD1982 and @Progi1984
